version: '2'

services:  
  database:
    image: ${DATABASE_VERSION}
    networks:
      - backend
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - mongo-data:/data/db
      - ./mongo/scripts:/scripts
      - ./mongo/data:/data
  web:
    build: ./web
    ports:
    - "5000:5000"
    networks:
      - backend
    depends_on:
      - database
        
networks:  
  backend:
    driver: bridge

volumes:  
  mongo-data: