version: '3'

services:  
  database:
    image: ${DATABASE_VERSION}
    networks:
      - backend
    container_name: ${DATABASE_CONTAINER_NAME}
    volumes:
      - mongo-data:/data/db
      - ./mongo/scripts:/scripts
      - ./mongo/data:/data
  flask:
    build: ./web
    ports:
    - "${FLASK_PORT}:${FLASK_PORT}"
    environment:
    - GUNICORN_CMD_ARGS=${GUNICORN_CMD_ARGS}
    volumes:
    - ./web:/web
    networks:
      - backend
    depends_on:
      - database
        
networks:  
  backend:
    driver: bridge

volumes:  
  mongo-data: